openapi: "3.0.0"
info:
  version: 1.0.0
  title: Movies Website
x-yc-apigateway:
  service_account_id: ${MOVIES_API_SA_ID}

paths:
  /:
    get:
      operationId: index
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${MOVIES_WEBSITE_BUCKET}
        object: 'Home.html'
  /{file+}:
    get:
      operationId: website
      parameters:
        - name: file
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${MOVIES_WEBSITE_BUCKET}
        object: '{file}'
